name = "dynamic-vercel-og"
main = "src/index.js"
compatibility_date = "2023-05-09"

compatibility_flags = [ "nodejs_compat" ]


base_dir = "src"

rules = [
  { type = "ESModule", globs = ["**/*.js"]},
  { type = "Data", globs = ["*.ttf"], fallthrough = true },
]